{% set name = "requests-file" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f549a3f3b0699415ac04d167e9cb39bccfb730cb832b4d20be3d9867356e658

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools_scm >=3.4.3
    - toml
    - wheel
  run:
    - python
    - requests >=1.0.0

test:
  source_files:
    - tests
  imports:
    - requests_file
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -m unittest -v tests
  requests:
    - pip
    - pytest

about:
  home: http://github.com/dashea/requests-file
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: file transport adapter for Requests
  description: |
    Requests-File is a transport adapter for use with the Requests 
    Python library to allow local filesystem access via file:// URLs.
  doc_url: https://github.com/dashea/requests-file/blob/master/README.rst
  dev_url: http://github.com/dashea/requests-file